### PR TITLE
Fix: No node available exception

### PR DESCRIPTION
**Pull request by srinivasa-vasu**
This is to fix the following scenario:

It so happens that the `partitionAwareNodes` could be non-empty from the TabletMetadata, but the state of the individual nodes could be down (like internal nodes not exposed to the client network). In such cases, `partitionAwareNodesInObjectArray` would be empty and the data insertion/retrieval fails with "No node available exception". Instead of it, it is expected to use the QueryPlan from the superclass that would use the liveNodes (contactPoints) to execute the request.

The way to simulate is to have 1 RF with 3 nodes or 3RF with 4/5 nodes etc. Expose the cluster through a load balancer and keep the tServer endpoints internal (non-routable from the client network)

### CODE REVIEW

**Review by nchandrappa — APPROVED** [review]
Code changes look good and will fix the scenario where `UpHostIterator` returns an empty list. The current code in `newQueryPlan` is present to handle the empty list scenario, however, there was a bug where we were checking `partitionAwareNodesInObjectArray != null` instead of the `!ArrayUtils.isEmpty(partitionAwareNodesInObjectArray)`

In 3.x driver, when `UpHostIterator` is empty, `newQueryPlan` of the child policy (DCAwareRoundRobinPolicy) gets called. The bug is not present on the `3.x` driver.

**Comment by tedyu** [comment]
lgtm

**Comment by kneeraj** [comment]
BTW, FWIW, this is the exact behaviour the new smart driver has. If it, for some reason, cannot connect to any node obtained from the embedded load-balancer then it falls back to the single endpoint given in the beginning.

**Comment by srinivasa-vasu** [comment]
`new UpHostIterator(statement, tableSplitMetadata.getHosts(key))` -> UpHostIterator was shuffling the source node list (from tableSplitMetadata) for local reads instead of its own local copy which is an unsafe thread operation. Updated the initialization part to use a local copy.

**Review by nchandrappa — APPROVED** [review]
LGTM. Code looks good for merging. Additional changes will be made during the testing of github issues: [10117](https://github.com/yugabyte/yugabyte-db/issues/10117). Code made here is valid and will be used in the code fix for #10117.

**Pull request merged**
