### PR TITLE
JAVA-2793: Add composite config loader

### PR DESCRIPTION
**Pull request by tedyu**
This ports commit bfbf82734c734e311cc9869ec351cbd3f127df4e from upstream.

### CODE REVIEW

**Comment by tedyu** [comment]
@cc @nchandrappa

**Review by nchandrappa — APPROVED** [review]
Hi Ted,

LGTM, Thanks for bringing the commit from upstream. 

Since we will have customers using this feature, can we add a test case for config loader in `yb-ycql-4x`. Thanks

**Comment by tedyu** [comment]
I will put config loader test on my radar.

**Pull request merged**
